### ISSUE TITLE
Default example fails to run

### ISSUE THREAD

**Issue by mostaphaRoudsari** [protyze/aframe-curve-component#1]
Hi @protyze,

Thank you for adding the curve component for A-Frame. It will be quite useful. I tried to run the example that you shared on download page to get started and it fails  to run. Any idea why this might be happening?

```html
<head>
  <title>My A-Frame Scene</title>
  <script src="https://aframe.io/releases/0.5.0/aframe.min.js"></script>
  <script src="https://unpkg.com/aframe-curve-component/dist/aframe-curve-component.min.js"></script> 
</head>
 
<body>
  <a-scene>
    <a-curve id="track1">
        <a-curve-point position="-1 1 -3"></a-curve-point>
        <a-curve-point position="1 1 -3"></a-curve-point>
    </a-curve>
    
    <!-- Draw the Curve -->
    <a-draw-curve curveref="#track1" material="shader: line; color: blue;"></a-draw-curve>
    
    <!-- Clone a Box along the Curve -->
    <a-entity clone-along-curve="curve: #track1; spacing: 0.2; scale: 1 1 1; rotation: 0 0 0;" geometry="primitive:box; height:0.1; width:0.2; depth:0.1"></a-entity>
  </a-scene>
</body>
```
Here is the error:

![image](https://cloud.githubusercontent.com/assets/2915573/25552574/87502c08-2c6b-11e7-9d01-1bd6d8f5a2e0.png)

Thanks.

**Comment by protyze** [comment]
Hi, You need to use A-Frame Master. It won't work with A-Frame 0.5.0 due to a bug in that Version. Although this only affects the Draw and Clone Sub-Components. If you use the Master-Version it will work: https://rawgit.com/aframevr/aframe/master/dist/aframe-master.min.js

See Basic example here: https://protyze.github.io/aframe-curve-component/

**Comment by mostaphaRoudsari** [comment]
Thanks @protyze. It worked once I changed both to master and build.js

```html
  <head>
    <script src="https://rawgit.com/aframevr/aframe/master/dist/aframe-master.min.js"></script>
    <script src="https://protyze.github.io/aframe-curve-component/build.js"></script>
  </head>
```
