### ISSUE TITLE
It would be great to have the other curve types working

### ISSUE THREAD

**Issue by elbobo** [protyze/aframe-curve-component#6]
Whenever you have a chance!

**Comment by protyze** [comment]
Just merged a pull request for that.

**Comment by elbobo** [comment]
that's great - have you released a new version with that change? I am trying it in aframe 1.0.1 and it still only produces one type of curve as far as I can see.

Creating and drawing a line as follows produces the same type of line regardless of what type I give it.

```
<a-entity id="track1" curve="closed: true; type: QuadraticBezier">
        <a-curve-point position="-1 1 -1"></a-curve-point>
        <a-curve-point position="0 2 -1"></a-curve-point>
        <a-curve-point position="1 1 -1"></a-curve-point>
</a-entity>

<a-draw-curve curveref="#track1" material="shader: line; color: blue;"></a-draw-curve>
```

I am using it incorrectly?
